name: yandex_mapkit_example
description: Demonstrates how to use the yandex_mapkit plugin.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  permission_handler: ^8.3.0

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
  yandex_mapkit:
    path: ../

flutter:
  assets:
    - lib/assets/user.png
    - lib/assets/cluster.png
    - lib/assets/place.png
    - lib/assets/arrow.png
    - lib/assets/route_start.png
    - lib/assets/route_stop_by.png
    - lib/assets/route_end.png
  uses-material-design: true
