name: yandex_mapkit
description: A Flutter plugin for integrating Yandex.MapKit in Android and iOS applications.
version: 0.3.9
homepage: https://github.com/Unact/yandex_mapkit

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  equatable: ^1.1.1
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.unact.yandexmapkit
        pluginClass: YandexMapkitPlugin
      ios:
        pluginClass: YandexMapkitPlugin
