name: yandex_mapkit
description: A Flutter plugin for integrating Yandex.MapKit in Android and iOS applications.
version: 4.0.2
homepage: https://github.com/Unact/yandex_mapkit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter_plugin_android_lifecycle: ^2.0.15
  equatable: ^2.0.5
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.unact.yandexmapkit
        pluginClass: YandexMapkitPlugin
      ios:
        pluginClass: YandexMapkitPlugin
